version: '3'
services:
  mkdocs:
    image: squidfunk/mkdocs-material
    container_name: Mkdocs-dwes2425
    ports:
      - "8005:8000"
    volumes:
      - ./:/docs
    stdin_open: true
    tty: true